### ISSUE TITLE
"update shell invocation" commit causes failures in a number of images that we care about

### ISSUE THREAD

**Issue by joebuilds** [amazonlinux/amazon-ec2-utils#29]
This commit cf8c1a2d9178632e9d91cf42deb6e3a8c73bc036 causes failures across a number of amis that we use, including:

* freebsd-12,13
* sles-12,15
* ubuntu-1604,1804
* rhel-6

Specifically, during instance initialization the script exits with this error:

```
/opt/aws/bin/ec2-metadata: /usr/bin/bash: bad interpreter: No such file or directory
```

Note the commit comment:

> bash is in /usr/bin everywhere we care about.  The /bin path is only there for backwards compatibility.

This is not true for the above images that my organization cares about; on these images `/usr/bin/bash` does not exist, and `/bin/bash` is not present as a backwards compatibility. What criteria do you use to determine if you 'care about' an OS? 

Was this change made to fix any real problem in new OS images?

**Comment by sean-simmons-progress** [comment]
following

**Comment by joebuilds** [comment]
After consideration, it's clear that the purpose of this org/repo is to support the amazonlinux OS in particular, and the fact that it happened to work on other OSes in the past is just chance. Going forward we will consider 1. pinning dependencies like this to specific releases, and 2. using the http metadata api directly or via an owned library.

I will leave this open for a time to give the maintainers a chance to state their disposition towards the use of the scripts in this repo on OSes like the ones mentioned above.

**Comment by nmeyerhans** [comment]
Hi @joebuilds. You're correct that we primarily target Amazon Linux with this package, but it is also distributed with Debian and Ubuntu, and is a default component of the Debian AWS AMIs. So we definitely are not limited to Amazon Linux.

Modern Fedora and Debian derivatives (including current versions of Amazon Linux and Ubuntu) have moved to a usrmerge filesystem layout by default, in which `/bin` no longer exists and all the content has moved to `/usr/bin`.  The `/bin` path still exists as a symlink for compatibility, but `/usr/bin` is the canonical location for these binaries. We moved to `/usr/bin/bash` to remove our dependency on the compatibility symlink. (See  [Fedora](https://fedoraproject.org/wiki/Features/UsrMove) and [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978636) information on this change.)

If you need to support older distro versions, or distros that haven't (yet) moved to a usrmerge layout, I recommend doing so in a branch that either reverts https://github.com/amazonlinux/amazon-ec2-utils/commit/cf8c1a2d9178632e9d91cf42deb6e3a8c73bc036 or modifies the shell invocation in the build process (e.g. in `debian/rules` or in the .spec file's `%build` or `%install` section)

**Comment by joebuilds** [comment]
Thank you for your attention.
